### ISSUE TITLE
Where is the main code

### ISSUE THREAD

**Issue by FBoyang** [zleizzo/DDGroup#1]
I have a question that may seem naive, but I am unable to locate the software beyond the README. Has the software been relocated to a different location?

**Comment by zleizzo** [comment]
My apologies, I just hadn't gotten around to doing the initial commit. The code has been added.

**Comment by FBoyang** [comment]
Great, but I am sorry to bother you again. I encountered the error when running the example code you gave in experiments.ipynb:
---> 15 hg_R = hard_grow_region(X[:, :-1], hg_labels, B, hg_args)
     16 ho_R = hard_opt_region(torch.tensor(X[:, :-1]), torch.tensor(ho_labels), torch.tensor(B), ho_args)

[/content/DDGroup/src/utils/methods.py](https://localhost:8080/#) in hard_grow_region(X, labels, B, center, speeds, tol, shrinkage)
    164 
    165     if center is not None:
--> 166         X2 -= center
    167         R  -= center.reshape((d, 1))
    168     if speeds is not None:

UFuncTypeError: Cannot cast ufunc 'subtract' output from dtype('O') to dtype('float64') with casting rule 'same_kind'
